root = "path/to/root/for/repos"
version_update_required = false  # true | false - if true, version will be updated in package.json
repo_rebuild_required = false  # true | false - if true, repo will be reinstall packages and rebuild
process_only_updated_repo = true  # true | false - if true, only repos will be processed that have changes in git
disable_checks = false  # true | false - if true, husky checks will be disabled on commit and push

[logger]
log_level = "Warn" # Debug | Info | Warn | Error

# version that should be set to the package on specific branch
[git]
version = "5.9.25" # 5.8.19a or comment for autodetect
branch = "source_branch_here"
release_branch = "release_branch_here"

[aws]
role_script_path="path/to/sso.zsh"
role="role_name_here"
sso_start_url="https://ORGANIZATION.awsapps.com/start/#/"

[repos]
node_workers = [
  'conform5-bpo-api',
]

python_workers = [
  'conform5-lambda-batch-vr-python-custom-code',
]



