root = "path/to/root/for/repos"
version_update_required = false  # true | false
repo_rebuild_required = false  # true | false
process_only_updated_repo = true  # true | false

# version that should be set to the package on specific branch
[git]
version = "1.2.3" # 1.2.3a or "" for autodetect
branch = "source_branch_here"
release_branch = "release_branch_here"

[aws]
role_script_path="path/to/sso.zsh"
role="role_name_here"

[repos]
node_workers = [
  'conform5-bpo-api',
]

python_workers = [
  'conform5-lambda-batch-vr-python-custom-code',
]



